#.github/workflows/phpinsights.yml
name: CI
on:
    - pull_request
    - push

jobs:
    phpinsights:
        runs-on: ubuntu-latest
        name: PHP Insights checks
        steps:
        - uses: actions/checkout@${GITHUB_REF_NAME}
        - name: PHP-Insights
          uses: docker://tigron/skeleton-test-phpinsights
          with:
            args: "-v --min-quality=70 --min-complexity=50 --min-architecture=50 --min-style=60 --ansi --format=github-action"

